### PR TITLE
6 maintenance commits, plus a file layout refactoring

### PR DESCRIPTION
**Pull request by gmarceau**

### CODE REVIEW

**Comment by jake-miles** [comment]
Could you describe briefly what was just moved and what was changed?

**Comment by gmarceau** [comment]
The commit names are a good reference

* New test for `strict`
* Error message on misuses of `isA`
* `optional` continues to accept `null` and `undefined`, but now rejects other falsy values. This is intended as a bug fix, but can be a breaking change depending on the usage.
* Test and doc dependencies moved to "devDependencies", where they should be
* The new `constructs` functionality now automatically checks the `this` argument on methods.
* Better display of `c.error` in contract error messages.
* Then last but not least, a file layout refactoring.

**Comment by jake-miles** [comment]
I guess I deserved that.  :) Reviewing now.

**Comment by jake-miles** [comment]
👍

**Comment by gmarceau** [comment]
awesomesauce

**Pull request merged**
